EN-465 Implement Blockfrost API on CDP for ENO relevant functions
Sbcdn/cdp pull request #23
Opened 2023-12-04 13:14 UTC by Eloi

Implement blockfrost as a new cardano data provider Allow blockfrost configuration from toml file
Allow selecting provider in config.toml

Endpoints migrated to be available for both dbsync/blockfrost providers:

 /api/info/utxos/{address}
 /api/info/address/exist
 /api/info/asset/metadata/{fingerprint}
 /api/info/history/address
 /api/info/pools/{page}
 /api/info/addresses/assets/
 /api/info/tokens/isNft/ (not supported)
 /api/info/history/discover/{hash} (not supported)
 /api/info/reward/amount/{stake_addr}
 /api/info/epoch/stake/amount/{stake_addr}/{epoch}

2024-01-25 18:57 UTC, stysouk requested changes

2024-02-05 13:30 UTC, Eloi commented on src/server/handler/handler_rest/info.rs
>  }
The gist of this is exactly to get the trait object, to use it later to perform operations on it.

2024-02-06 09:52 UTC, stysouk approved these changes

2024-02-14 13:39 UTC, Sbcdn approved these changes

2024-02-14 13:40 UTC, merged